language: python
python:
- '3.6'
- '3.7'
install: pip install tox-travis
script: tox
notifications:
  webhooks:
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
    if: branch = master
    urls:
      secure: qyCg6Fdk9NqLVLBcldNkag1522uYsKuf9Z5uX8uXVI8+aEJdKkt+T+RHZmLboCbEMnih293h3iXwcm47wZcdpWe28nS8DOa6aw15tg4mjSvqTUeZEID2/IqJECHfOfZqDgTIfnoc5gsEZjEbHijv/y2R4sScCfxdGca8epdjJiGm8Ao+kLB5k4SSaJhQTdWitBSMnu+GGnlYgyJ1ITAgvhDCLhNV+vnuObTTNrnOcXkoGjMkxhKAZ76D7s14OlxBwd702eRmn+H+jdcYYLu+/oh5B9C+OLoMnQFIcqpD/NpfXd4QQWBW9f358D2+BiXxsWFjjYf18W5+XXUUSp386Ath9HR8Mz/2tlZdJuKDAxO6UAZDcmAoc/qFIafdB3jCL/wi+JnJlDxTAZy39q8mrmwwOoFSz3zW7nV/CnOhXUdDIopDV7OjPv8AKX5xxHlxssBIXEQrLqjP66QnPAhQ3YCf2dKzOJutnLpH3nVYahfu1+OpX4LLvAaJYdVJ7PpoHfBiO+YtasKw0ImS0nZMTWOZFUu+PVIz6wS3NPPZxcJPHFGY/33Vnq0mzGBHvYXFKmQB06cQYXTFNvfMJRXMzoUNxbsF6y6cmP1u6JlhIRpMvQU16Q5PjmOf6OFtHclyyKTA7H8YRDNezaBqDQys4HyHFoU/rJDdyFHBzpGxNvY=
      # deploy to appuio.ch
